name: ethosTDSenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22.3.1
  - numpy==1.23.4
  - pandas==1.5.1
  - matplotlib==3.6.2
  - seaborn==0.12.1
  - jupyter=1.0.0
  - nltk=3.7
  - gensim=4.2.0
  - spacy=3.4.3
  - scikit-learn==1.1.3
